package wiretypes

import (
	"encoding/json"
	"net/http"
)

type ResponsePayloadType string

const (
	ResponsePayloadJSONRPC   ResponsePayloadType = "jsonrpc_response"
	ResponsePayloadNotifyAck ResponsePayloadType = "notify_ack"
)

// TunnelResponsePayload mirrors the body posted to POST /v1/tunnel/{tunnel_id}/response when
// delivering MCP results back to tunnel-service.
type TunnelResponsePayload struct {
	RequestID       string              `json:"request_id"`
	JSONRPCResponse json.RawMessage     `json:"rpc_resp,omitempty"`
	ResponseHeaders http.Header         `json:"resp_headers,omitempty"`
	ResponseCode    int                 `json:"resp_code,omitempty"`
	ResponseType    ResponsePayloadType `json:"resp_type,omitempty"`
}

// RawPolledCommand represents a single JSON object returned by
// GET /v1/tunnel/{tunnel_id}/poll before it is converted into the strongly typed
// controlplane.PolledCommand interface.
type RawPolledCommand struct {
	RequestID string `json:"request_id"`
	// ShardToken is an opaque value generated by tunnel-service to associate
	// this command with the backend shard or worker responsible for handling
	// its lifecycle. Clients MUST treat this value as opaque and MUST echo
	// it back when posting the response via the HTTP header
	// `X-Tunnel-Shard-Token`. The JSON body of the response MUST NOT contain
	// this token.
	ShardToken string          `json:"shard_token"`
	JSONRPC    json.RawMessage `json:"jsonrpc"`
	CreatedAt  string          `json:"created_at"`
	Headers    http.Header     `json:"headers"`
}

// PolledCommandEnvelope is the top-level container returned by
// GET /v1/tunnel/{tunnel_id}/poll that groups pending requests for a tunnel.
type PolledCommandEnvelope struct {
	Commands []RawPolledCommand `json:"commands"`
}
